### ISSUE TITLE
osascript: not found

### ISSUE THREAD

**Issue by dragonxtek** [backyardbiomech/qtiConverter#1]
I run bank1 and testformula without issues, but bank2 returns this error:

> /bin/sh: 1: osascript: not found
> /bin/sh: 1: osascript: not found
> Traceback (most recent call last):
>   File "./qtiConverterApp.py", line 925, in <module>
>     doIt.run()
>   File "./qtiConverterApp.py", line 166, in run
>     f.write(self.writeText + '\n')
> AttributeError: 'makeQti' object has no attribute 'writeText'

**Comment by backyardbiomech** [comment]
@dragonxtek , bank2 works for me without error. Even if you can't get bank2 to work, you should be able to use the program on your own banks. bank2.txt has some complicated formatting features in it.

Please reply with your macOS version.

Also, in a terminal, try
```
which osascript
```
and paste the output here (if any).

Also, try

```
echo PATH
```

and paste the output here.

**Comment by dragonxtek** [comment]
Thanks for your quickly response
I'm working on Ubuntu 18.04 LTS
I installed osascript with pip3 install osascript and I checked that is it working.
But I still have the same issue
![image](https://user-images.githubusercontent.com/10552658/80131625-80aaed80-8568-11ea-9816-b8bba52bea18.png)

**Comment by backyardbiomech** [comment]
Ah, ok. I don't have an Ubuntu install to test on right now, and I have never tested this application on linux. 
The osascript is a way for python to call applescripts, which is how I display a warning dialog on Mac. I don't think it does anything on linux.

I just pushed a new edit that should print the error to your command line, making this a bit more cross-platform. Please re-download the main script.

However, since I cannot reproduce the error with bank2.txt, I can't do much more. Since it works with the other test files, please try with your own question banks, and let me know if you run into specific problems. `bank2.txt`is designed to test some tricky formatting styles that are unlikely in most question banks.

**Comment by dragonxtek** [comment]
Thanks,
Now I could see where was the problem.
![Selection_866](https://user-images.githubusercontent.com/10552658/80268453-fc925c00-8674-11ea-9838-f8334d1dc04e.png)

The problem was the image names in bank2. Just replace testimage.png by testImage.png on both questions and the problem is solved.

**Comment by backyardbiomech** [comment]
There must be a difference in how linux vs. macOS handle capitalization then. Thanks for finding that. I've changed bank2.txt to avoid future errors.
